"""Add image_svg

Revision ID: 1cf9289f4c8c
Revises: d35474d8ca38
Create Date: 2026-04-16 22:00:31.023156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf9289f4c8c'
down_revision: Union[str, None] = 'd35474d8ca38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('image_svg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'image_svg')
    # ### end Alembic commands ###